### ISSUE TITLE
ModuleNotFoundError when running tests on Python 3.11

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#172] opened 2023-09-04 09:05 UTC
Seen in current `plone.app.event` and `plone.app.uuid`.

```
$ tox -e test
...
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/bin/zope-testrunner", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/__init__.py", line 31, in run
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/__init__.py", line 55, in run_internal
    runner.run()
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/runner.py", line 187, in run
    feature.global_setup()
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 527, in global_setup
    tests = find_tests(self.runner.options, self.runner.found_suites)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 176, in find_tests
    for suite in found_suites:
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 197, in find_suites
    for fpath, package in find_test_files(options):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 265, in find_test_files
    for f, package in find_test_files_(options):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 293, in find_test_files_
    for (p, package) in test_dirs(options, {}):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 348, in test_dirs
    p = import_name(p)
        ^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.uuid/.tox/test/lib/python3.11/site-packages/zope/testrunner/find.py", line 425, in import_name
    __import__(name)
ModuleNotFoundError: No module named 'plone.app.uuid'
```

See for example this [github-actions run](https://github.com/plone/plone.app.event/actions/runs/6070677591/job/16467203000).

I have tried a few things locally, but without effect:

* Use the `constraints.txt` of 6.0.5 instead of 6.0-dev.
* Add `Products.CMFPlone` to the dependencies.
* Use an older tox (and older pyproject-api: with latest pyproject-api I get errors parsing our config unless I have latest tox as well):
  * `pip install tox==4.10.0 pyproject-api==1.5.3`
  * `tox==4.5.1 pyproject_api==1.5.1`
  * `tox==4.4.1 pyproject_api==1.5`

What?  When I install tox in a virtualenv with Python 3.10, it works!  Until now I was using 3.11.  Both 3.11.4 and 3.11.5 fail.

Ah, and of course the Python version that tox itself uses does not really matter.  When I undo my changes and just use latest tox on Python 3.11, but add `base_python = 3.10` in `[testenv:test`], then it passes.

Any idea why 3.11 would fail?

**Comment by mauritsvanrees** [comment] 2023-09-04 10:28
Strangely, in `plone.session` it works fine.

**Comment by mauritsvanrees** [comment] 2023-09-04 11:59
Comparing a tox env on 3.10 with 3.11 one difference is some editable finder:

```
$ diff test310/lib/python3.10/site-packages/__editable___plone_app_uuid_2_2_3_dev0_finder.py test311/lib/python3.11/site-packages/__editable___plone_app_uuid_2_2_3_dev0_finder.py 
2c2
< from importlib.machinery import ModuleSpec
---
> from importlib.machinery import ModuleSpec, PathFinder
16,19c16,19
<         for pkg, pkg_path in reversed(list(MAPPING.items())):
<             if fullname == pkg or fullname.startswith(f"{pkg}."):
<                 rest = fullname.replace(pkg, "", 1).strip(".").split(".")
<                 return cls._find_spec(fullname, Path(pkg_path, *rest))
---
>         # Top-level packages and modules (we know these exist in the FS)
>         if fullname in MAPPING:
>             pkg_path = MAPPING[fullname]
>             return cls._find_spec(fullname, Path(pkg_path))
20a21,29
>         # Handle immediate children modules (required for namespaces to work)
>         # To avoid problems with case sensitivity in the file system we delegate
>         # to the importlib.machinery implementation.
>         parent, _, child = fullname.rpartition(".")
>         if parent and parent in MAPPING:
>             return PathFinder.find_spec(fullname, path=[MAPPING[parent]])
> 
>         # Other levels of nesting should be handled automatically by importlib
>         # using the parent path.
```

When I copy the file from 3.10 to 3.11, and call `zope-testrunner` directly, so without calling tox, then the 3.11 job works.
This file gets updated when you call `./bin/pip install --no-deps -e  ../../` in the tox env, which is what tox itself normally does.

**Comment by mauritsvanrees** [comment] 2023-09-04 14:03
The problem is `setuptools`.  One of the changes in [68.1.0](https://setuptools.pypa.io/en/latest/history.html#v68-1-0) has broken this.  I suspect "Made imports in editable installs case-sensitive on case-insensitive filesystems".  68.1.1 already had a fix, but it seems more is needed.  Maybe it now works with one-level namespaces (`plone.session`) and not with two-level namespaces (`plone.app.uuid`).

With the following added to `pyproject.toml`, it works again:

```
[build-system]
# See https://snarky.ca/what-the-heck-is-pyproject-toml/
requires = ["setuptools<68.1.0", "wheel"]
build-backend = "setuptools.build_meta"
```

Note that if you do not have a version restriction in here, or do not have this section at all, `pip` will use the latest `setuptools` version, instead of using what is in your local virtualenv.

**Comment by abravalheri** [comment] 2023-09-04 18:16
Thank you very much @mauritsvanrees, thank you very much for opening the issue.

This is my take on the minimal reproducer:

```bash
> docker run --rm -it python:3.11-bullseye /bin/bash

mkdir -p /tmp/pkg1/plone/app/uuid
cd /tmp/pkg1    
echo '__import__("pkg_resources").declare_namespace(__name__)' > plone/__init__.py
echo '__import__("pkg_resources").declare_namespace(__name__)' > plone/app/__init__.py
echo 'print(f"hello world {__name__}")' > plone/app/uuid/__init__.py
cat <<EOF > setup.py
from setuptools import setup, find_packages

setup(
    name="plone.app.uuid",
    version="42",
    packages=find_packages(),
    namespace_packages=[
        "plone",
        "plone.app",
    ]
)
EOF
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==68.1.2", "wheel"]
build-backend = "setuptools.build_meta"
EOF

mkdir -p /tmp/pkg2/plone/app/other
cd /tmp/pkg2
echo '__import__("pkg_resources").declare_namespace(__name__)' > plone/__init__.py
echo '__import__("pkg_resources").declare_namespace(__name__)' > plone/app/__init__.py
echo 'print(f"hello world {__name__}")' > plone/app/other/__init__.py

cat <<EOF > setup.py
from setuptools import setup, find_packages

setup(
    name="plone.app.other",
    version="42",
    packages=find_packages(),
    namespace_packages=[
        "plone",
        "plone.app",
    ]
)
EOF
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==68.1.2", "wheel"]
build-backend = "setuptools.build_meta"
EOF


cd /tmp
python3.11 -m venv .venv
.venv/bin/python -m pip install -U 'pip==23.2'
.venv/bin/python -m pip install -e pkg1
.venv/bin/python -m pip install -e pkg2
.venv/bin/python -c 'from plone.app import uuid, other; print(uuid, other)'
```

I think this is related to the fact that it is very hard to support `pkg_resources`-style namespace packages with PEP 660, the main reason being that `pkg_resources.declare_namespace` requires a special `-nspkg.pth` file to be produced.

I have the impression that the `-nspkg.pth` was already broken before `68.1.0` but it was masked by the specific implementation of the finder.

I also think that changing the finder again would not be a good option. Personally, I don't know how to solve this problem without using the logic that was previously implemented in the Finder, but that was problematic from the point of view of case sensitivity.
I also would not like to add the churn of handling file system case sensitivity on `setuptools` itself as initially suggested in #3995 (it not only hinders maintenance but also decrease performance), so I still believe the best is to delegate to the stdlib's import machinery.

So my best bet right now is that the best way to solve this problem is to fix the `-nspkg.pth` file. I think the problem is in the file name, for some reason 2 packages that share the same namespace are creating 2 identical file names that end-up overwriting themselves. This only occurs if the file name contains `.`.

**Comment by gforcada** [comment] 2023-09-15 13:57
🤔 so this means that we are not pinning `setuptools` in any way, and we get newer versions as they come out 😖 

Given that our pkgutil namespaces are deprecated, there is bound to happen more and more often I guess.

**Comment by mauritsvanrees** [comment] 2023-09-20 20:36
> Given that our pkgutil namespaces are deprecated, there is bound to happen more and more often I guess.

`pkgutil` namespaces exist too, but we use `pkg_resources` namespaces.  But yes, both are deprecated, and we should move to native namespaces at some point (Plone 7 likely).

I guess we should port the change from https://github.com/plone/plone.app.event/pull/385 to plone/meta.  We can do that if/when we see problems in more packages.

Letting all packages use a `src` directory helps avoid some problems, no matter what kind of namespaces we use.  https://github.com/plone/plone.app.event/pull/384 is an example for that.  I would be in favour of doing that for all Plone packages.

**Comment by gforcada** [comment] 2023-10-14 16:37
Fast forward 3 weeks, the fixes you help drive on setuptools landed on `68.2.0` 🎉 

Should we enforce

```toml
[build-system]
requires = ["setuptools>=68.2", "wheel"]
```

On all packages then? 🤔

**Comment by mauritsvanrees** [comment] 2023-10-17 20:25
Yes, I think this would be good.  Let me prepare a PR.

**Comment by gforcada** [comment] 2023-11-12 16:45
We forgot to close this.

**Closed by gforcada** 2023-11-12 16:45 UTC
Labels: 01 type: bug, 13 prio: normal, 43 lvl: complex
