### ISSUE TITLE
Detect when options are set twice

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#107] opened 2023-05-30 12:53 UTC
I tried latest meta on `plone.app.caching`, but got an error when running `towncrier`:

```
$ tox -e release-check
release-check: install_deps> python -I -m pip install build towncrier twine -c https://dist.plone.org/release/6.0-dev/constraints.txt
release-check: commands[0]> towncrier build --version=100.0.0 --yes
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/bin/towncrier", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/towncrier/build.py", line 112, in _main
    return __main(
           ^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/towncrier/build.py", line 140, in __main
    base_directory, config = load_config_from_options(directory, config_file)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/towncrier/_settings/load.py", line 73, in load_config_from_options
    config = load_config(base_directory)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/towncrier/_settings/load.py", line 100, in load_config
    return load_config_from_file(directory, config_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/.tox/release-check/lib/python3.11/site-packages/towncrier/_settings/load.py", line 105, in load_config_from_file
    config = tomllib.load(conffile)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
tomllib.TOMLDecodeError: Cannot overwrite a value (at line 91, column 72)
release-check: exit 1 (0.51 seconds) /Users/maurits/community/plone-coredev/6.0/src/plone.app.caching> towncrier build --version=100.0.0 --yes pid=7139
  release-check: FAIL code 1 (9.45=setup[8.94]+cmd[0.51] seconds)
  evaluation failed :( (9.62 seconds)
```

Problem is that `plone.app.caching` has this in `.meta.toml`:

```
[dependencies]
mappings = [
    "Zope = ['OFS', 'Products.Five', 'Products.PageTemplates', 'ZPublisher']",
    "python-dateutil = ['dateutil']",
    ]
```

plone/meta adds this to `pyproject.toml`, but these mappings already exist, so they are double, and the file cannot be parsed.  I will fix it in `plone.app.caching`.

I wonder if this is easy to detect, or if this is just something to fix in individual packages.  There will be similar problems with other config options.

**Comment by gforcada** [comment] 2023-06-27 00:52
Another option might be #142 so after configuring the packages we lint/verify that their syntax is valid, and otherwise we loudly error? 🤔

**Comment by gforcada** [comment] 2023-10-14 12:18
Duplicate of #142

**Closed by gforcada** 2023-10-14 12:18 UTC
